# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 096d39437598ad940c6b2764c1b2a7637e163fe446821b9ea4b03a32ba6df6ae421c250cd4f9788f50c27be0786014b9f545e99f58e9300323dd8be7f2639ad7

test:
  secret_key_base: d0553768cf50d8b36d60ac87315a6f6a3373d1c71e4dbd9b04a677ba55ff0c659c7ab946196c81244d41746eb7d0e00cd57260962cd458f148638c1097616cea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
